### ISSUE TITLE
[PS] Hash

### ISSUE THREAD

**Issue by holim0** [fe-interview-study/interview-question#1]
### 질문 (오픈형)

 하나의 해시 테이블이 존재합니다. 해시 테이블에 계속해서 데이터를 넣게 되고 이렇게 넣게 되면 충돌이 일어날 것입니다. 

충돌을 해결하기 위해서는 opening addressing 과 chaining 기법을 사용할 수 있지만 bucket은 한정되어 있어 opening addressing 방법을 사용할 수 없습니다. 

또한 계속해서 데이터가 들어오기 때문에 chaining 기법을 사용하면 해시 테이블의 효율성이 줄어들게 됩니다. 

그렇다면 이 상황에서 어떻게 해시 테이블을 설계를 해야 해시 자료구조가 가진 효율성을 높일 수 있을까요?

**[참고 그림]**

![R1280x0](https://user-images.githubusercontent.com/48006103/111300432-6acc7c80-8694-11eb-9313-a1ee6ec91f8e.png)

**Comment by cos18** [comment]
박성우: 해시 함수를 두개 사용해 다차원으로 들어가면 되지 않을까?

이호찬: 효율성에 집중을 함. 이중 해싱으로 생각하면 되지 않을까? 이중으로 사용한다면 데이터를 더욱 균일하게 분포할수 있을것이다. 다만 다차원이 아니라 이중으로 쓴 이유는 더욱 고차원으로 갈수록 더욱 균일할지는 의문이라 이중으로 생각함. 페이징(운체)과 관련이 있을듯?

박소현: 해시 함수에 대한 개선도 있지 않을까? 답이 있을까?
