### ISSUE TITLE
[Javascript] Event Loop란 무엇인가요?

### ISSUE THREAD

**Issue by hochan222** [fe-interview-study/interview-question#10]
[Javascript] Event Loop란 무엇인가요?

**Comment by cos18** [comment]
박성우: 작동방식까지 같이 설명
이희제: Event loop은 콜스택, 콜백큐를 확인하면서 콜스택이 비어있을떄 콜백큐 하나를 꺼내와 콜스택에 쌓는것. 
임광열: Task queue... -> Micro task queue
![](http://sculove.github.io/blog/2018/01/18/javascriptflow/promise-step2.png)

이호찬: 애니메이션 프레임의 우선순위가 변동될수 있음...
