### ISSUE TITLE
[OS] 프로세스와 스레드의 차이는 무엇인가요?

### ISSUE THREAD

**Issue by igy95** [fe-interview-study/interview-question#11]
[OS] 프로세스와 스레드의 차이는 무엇인가요? (단답형)

**Comment by cos18** [comment]
이희제: 스레드는 프로세스에가 할당받은 작업을 하는 작업단위.
꼬리질문... 멀티프로세스 vs 멀티스레드
가장 큰 차이는 컨텍스트 스위칭 차이
멀티스레드가 컨텍스트 스위칭 덜일어나 기회비용이 작게든다
통신방법
mutex

이호찬: Process is a program in execution. 스레드는 프로세스에서 들어가는 여러 흐름단위.
예시로 오류가 발생했을때... 프로세스는 강제종료하게 되면 독립적이니 괜찮지만 스레드는 하나라도 세그폴트뜨면 다 죽음
![](https://gmlwjd9405.github.io/images/os-process-and-thread/multi-thread.png)
