### ISSUE TITLE
[JS] 함수 선언문과 표현식

### ISSUE THREAD

**Issue by holim0** [fe-interview-study/interview-question#17]
### 질문

- 함수 선언문과 표현식에 대해서 각각 설명해주시고 차이점을 말씀해주세요.

**Comment by cos18** [comment]
박소현: 표기의 차이, 선언문의 경우에는 정의만 해놓은 것 뿐이고, 표현식은 변수처럼 사용하는 함수...
비교1. 호이스팅 / 비교2. 함수명 존재 유무

박성우: 차이점 위주로 많이 이야기할듯. 비교 2가지는 소현님과 동일

이호찬: 컴파일 타임 vs 런타임 -> 이 차이점 때문에 호이스팅과 익명함수

이희제: 호이스팅을 중점적으로 이야기할듯. 함수 선언문은 객체로 인식. 표현식은 변수에 대한 호이스팅으로 처리됨.
함수가 객체로 인식? -> 함수는 객체다. -> 왜?? 일단 나중에...
