### ISSUE TITLE
Issue title 제안 사항

### ISSUE THREAD

**Issue by hochan222** [fe-interview-study/interview-question#2]
어처피 close로 닫고 날짜는 README에 표시돼있으니 issue 제목을 [분야] 관련 지식

- ex) [PS] Hash
- ex) [JavaScript] Behavior Delegation

와 같이 명시하는건 어떤가요?

**Comment by holim0** [comment]
좋아요 :)

**Comment by hochan222** [comment]
`+ 추가`
<img src="https://user-images.githubusercontent.com/22424891/111315918-2b0e9080-86a6-11eb-952e-36d289180499.png" height="150px" />

칸반보드를 추가했습니다. 그 주 issue는 __신규이슈__ 에 완료된 이슈는 오른쪽 알맞은 분야 칸에 놓으려고하는데 어떤가요?

**Comment by holim0** [comment]
진행 상황 깔끔하게 알 수 있어서 아주 좋습니다
