### ISSUE TITLE
[React] useEffect 와 useLayoutEffect의 차이점에 대해서 설명해주세요

### ISSUE THREAD

**Issue by holim0** [fe-interview-study/interview-question#25]
➡️ [React] useEffect 와 useLayoutEffect의 차이점에 대해서 설명해주세요

**Comment by cos18** [comment]
호찬: 랜더링 시점

공식문서 -> useLayoutEffect를 쓰기 전 useEffect를 써보면서 필요가 있을 떄 써보자.
useEffect류 hooks는 ssr일때 js가 다 로딩 된 이후 실행된다. (랜더링 된 이후 js가 로딩이 되지 않는 경우 이를 기다려 실행한다)

성우: 동기, 비동기 
희재: 실행시점, 깜박이는 경우 useLayoutEffect가 이를 막아줌

메인페이지에 들어왔을때 상품 이미지 띄울때

useEffect으로 거의 처리가능하지 않나? useLayoutEffect를 쓸 일이 있나?
-> 데이터 처리 시간이 너무 짧아서 깜빡이는게 거슬리는 경우 쓰면 될것같음...?
