### ISSUE TITLE
[JS] Event Bubbling, Capturing에 대해서 설명해 주세요

### ISSUE THREAD

**Issue by JaeSeoKim** [fe-interview-study/interview-question#28]
> Event Bubbling, Capturing에 대해서 설명해 주세요

**Comment by cos18** [comment]
Event Bubbling : 하위 -> 상위 (넷스케이프 - win)
Event Capturing: 상위 -> 하위 (MS - lose)

인덱싱이 필요한 경우 이벤트 버블링을 실행할 수 있을까?

**Comment by JaeSeoKim** [comment]
[answer](https://github.com/fe-interview-study/interview-question/blob/main/0413/JaeSeoKim_0413.md#js-event-bubbling-capturing%EC%97%90-%EB%8C%80%ED%95%B4%EC%84%9C)

<img width="457" alt="event-bubble" src="https://user-images.githubusercontent.com/48559454/114552883-01925600-9ca0-11eb-99e0-a82b47cc7ced.png">

<img width="459" alt="event-capture" src="https://user-images.githubusercontent.com/48559454/114552889-035c1980-9ca0-11eb-9d8e-42fc821add4d.png">
