### ISSUE TITLE
[Network] 브라우저 주소창에 URL(https://www.google.com) 입력시 발생하는 일?

### ISSUE THREAD

**Issue by hochan222** [fe-interview-study/interview-question#3]
### 질문 (오픈형)

<img src="https://user-images.githubusercontent.com/22424891/111315100-652b6280-86a5-11eb-9b27-5b013268cba1.png" height="50px" />

holee는 검색을 하기 위해 브라우저 주소창에 다음과 같은 URL(https://www.google.com) 을 입력했다. 어떤 일이 발생할까?

**Comment by cos18** [comment]
박소현: 포인트가 어딘지 두는게 중요할듯. 네트워크에 중점을 줄지, 아님 화면 렌더에 중점을 줄지... 화면 렌더에 중점을 두어 답변을 드린 것 같다. 아는대로 말해봐라... 이런 느낌의 발문을 하심. differ-sync, reflow, repaint등 렌더링쪽에서도 세심한, 디테일한 답변이 가능할거같음.

임광열: 한줄 내외로 요약해 설명하려 함.

박성우: OSI이야기까지... 이건 핵심에 벗어나는거 아닌가?

이호찬: 이 문제가 스터디의 시작이자 끝임. 이 문제로 모든 지식을 말할 수 있음.
