### ISSUE TITLE
[React] 고차컴포넌트(HOC, Higher Order Component)란 무엇이고 언제 사용하는지 설명해주세요.

### ISSUE THREAD

**Issue by JaeSeoKim** [fe-interview-study/interview-question#33]
고차컴포넌트(HOC, Higher Order Component)란 무엇이고 언제 사용하는지 설명해주세요.

**Comment by cos18** [comment]
성우: hoc는 컴포넌트를 만드는 함수. 근데 매개변수를 받는... 재사용성 up 재조립
희제: 반복되는 로직을 줄이고 재사용성 높이는 용도.

상속 vs HoC
react에서 상속을 지양해야 함... 상속은 종속성을 가지지 않나?
[참고 공식 문서](https://ko.reactjs.org/docs/composition-vs-inheritance.html#so-what-about-inheritance)
