### ISSUE TITLE
[Network] TCP/IP 프로토콜의 4계층에 대해서 설명해주세요

### ISSUE THREAD

**Issue by holim0** [fe-interview-study/interview-question#42]
TCP/IP 프로토콜의 4계층에 대해서 설명해주세요

**Comment by cos18** [comment]
재서: 상용적 사용. 각각 계층 설명
호찬: vs OSI 7계층, 만들어진 이유, 이더넷
성우: 정의, 계층 설명
희제: 계층 설명
