### ISSUE TITLE
[React] setState

### ISSUE THREAD

**Issue by igy95** [fe-interview-study/interview-question#5]
왜 state를 직접 변경하지 않고 setState를 이용하나요? (단답형)

**Comment by cos18** [comment]
박성우: 리엑트의 랜더링 과정에 의해 필요하기 때문.

이호찬: this.state는 컴포넌트를 다시 랜더링하지 않기 때문.

박소현: state가 immutable하기 떄문에 덮어씌우기로 변경해야되기 때문에. 리엑트 로직을 설명할때, state에 그냥 새로운 객체 넣으면 immutable유지되는데 굳이 setstate 사용해야하는지? 질문을 받아서... -> [Reconciliation](https://ko.reactjs.org/docs/reconciliation.html)...!! [관련 이슈](https://github.com/facebook/react/issues/11527#issuecomment-360199710)

임광열: "상태 불변성 유지"가 중요. observer pattern ~= react
