### ISSUE TITLE
[Network] TCP와 UDP의 차이점은?

### ISSUE THREAD

**Issue by holim0** [fe-interview-study/interview-question#9]
### 질문

- TCP와 UDP를 어떻게 다른지 차이점을 중심으로 각각 설명해주세요. (단답형)

**Comment by cos18** [comment]
임광열: 신뢰성 중요함

박성우: 순서보장인데 광열님보다 답변 잘 못할듯

이호찬: 3단계 답변... 뒤의 예시 설명하는게 좋은것같음. (TCP / UDP 어디서 사용하는지...)

이희제: "연결" 관련되게 설명

실사용예 -> UDP 실시간 동영상 서비스
비유할 사물 이런거 생각하면 좋을듯

TCP vs TCP 서버는 다르게 말해야되지 않을까...

이 질문도 오픈형으로 확장 가능하지 않을까...
->오픈형처럼 장황하게 작성할려면 그 개념에 대한 체계가 확실하게 잡혀야될것 같음.
면접은 결국 핑퐁, 티키타카 이런거라 장황하게 말하면 부정적 영향

**Comment by holim0** [comment]
- 흐름제어랑 혼잡제어 차이는?
